---

# May be the name of any adapter in source/adapters
adapter: base

# May be any language code in source/languages
language: en

# An array of names of players found in source/players
players: [html, iframe, img, qt, wmp]

# YES to compress the code, NO to use the source code
compress: NO

# The directory to output the build to
target: build
